"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-05 21:27:15.050773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_email'), 'platform_admins', ['email'], unique=True)
    op.create_table('salons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled_modules', sa.JSON(), nullable=False),
    sa.Column('template_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salons_slug'), 'salons', ['slug'], unique=True)
    op.create_table('content_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=5000), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'key', name='uq_content_block_salon_key')
    )
    op.create_index(op.f('ix_content_blocks_salon_id'), 'content_blocks', ['salon_id'], unique=False)
    op.create_table('gallery_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_items_salon_id'), 'gallery_items', ['salon_id'], unique=False)
    op.create_table('salon_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salon_admins_email'), 'salon_admins', ['email'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_salon_id'), 'services', ['salon_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_salon_id'), 'staff', ['salon_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'scheduled_at', name='uq_booking_staff_slot')
    )
    op.create_index(op.f('ix_bookings_salon_id'), 'bookings', ['salon_id'], unique=False)
    op.create_table('staff_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_availability_staff_id'), 'staff_availability', ['staff_id'], unique=False)
    op.create_table('staff_services',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_services')
    op.drop_index(op.f('ix_staff_availability_staff_id'), table_name='staff_availability')
    op.drop_table('staff_availability')
    op.drop_index(op.f('ix_bookings_salon_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_staff_salon_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_services_salon_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_salon_admins_email'), table_name='salon_admins')
    op.drop_table('salon_admins')
    op.drop_index(op.f('ix_gallery_items_salon_id'), table_name='gallery_items')
    op.drop_table('gallery_items')
    op.drop_index(op.f('ix_content_blocks_salon_id'), table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index(op.f('ix_salons_slug'), table_name='salons')
    op.drop_table('salons')
    op.drop_index(op.f('ix_platform_admins_email'), table_name='platform_admins')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
