"""add salon_leads table

Revision ID: 7e0680c5dc8b
Revises: 8265c017c9a6
Create Date: 2026-07-22 10:41:59.361216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0680c5dc8b'
down_revision: Union[str, None] = '8265c017c9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salon_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salon_leads')
    # ### end Alembic commands ###
